name: chicago
version: 0.2.0-dev
repository: https://github.com/tvolkert/chicago

description:
  The Chicago widget set is an alternate design language for Flutter designed
  for desktop (keyboard and mouse) form factors. It is based on Apache Pivot.

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  collection: any
  intl: any

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
